excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://KaushalElsewhere.github.io
title: Kaushal Elsewhere
tagline: A log of everyday life
description: My awesome new site
paginate: 5